FROM node:24-alpine

WORKDIR /app

# Copy root monorepo manifests
COPY package.json tsconfig.json ./
COPY shared/package.json ./shared/
COPY frontend/package.json ./frontend/

# Install dependencies (workspaces will link automatically)
RUN npm install --legacy-peer-deps


WORKDIR /app/frontend

EXPOSE 3000

CMD ["npm", "run", "dev"]
