FROM node:24-alpine

WORKDIR /app

# Copy root monorepo manifests
COPY package.json tsconfig.json ./
COPY shared/package.json ./shared/
COPY backend/package.json ./backend/

# Install dependencies (workspaces will link automatically)
RUN npm install --legacy-peer-deps


WORKDIR /app/backend

EXPOSE 3001

CMD ["npm", "run", "start:dev"]
